server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackUri: forward:/userServiceFallBack
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/api/v1/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-SERVICE
                fallbackUri: forward:/departmentFallBack

##Resilence4J Configurations
#resilience4j:
#  circuitbreaker:
#    instances:
#      USER-SERVICE:
#        registeredHealthIndicator: true
#        eventConsumerBufferSize: 10
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        failureRateTreshold: 50
#        minimumNumberOfCalls: 5
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowSize: 10
#        waitDurationInOpenState: 5s
#        slidingWindowType: COUNT_BASED
#      DEPARTMENT-SERVICE:
#        registeredHealthIndicator: true
#        eventConsumerBufferSize: 10
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        failureRateTreshold: 50
#        minimumNumberOfCalls: 5
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowSize: 10
#        waitDurationInOpenState: 5s
#        slidingWindowType: COUNT_BASED

#Hystrix Configurations
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

#Actuator Configurations
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: hystrix.stream, health, info

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost